services:
- type: web
  name: iphotos-backend
  env: node
  plan: free
  buildCommand: npm install
  startCommand: npm start
  envVars:
    - key: CLIENT_URL
      value: https://iphoto-frontend.onrender.com/
    - key: MONGO_URI
      value: your_mongodb_uri
    - key: JWT_SECRET
      value: your_secret
  rootDir: backend

- type: web
  name: iphotos-frontend
  env: node
  plan: free
  buildCommand: npm install && npm run build
  startCommand: serve -s build
  envVars:
    - key: REACT_APP_API_URL
      value: https://iphotos-backend.onrender.com/api # cập nhật theo tên service backend
  rootDir: frontend